apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: letro-server
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
      labels:
        app.kubernetes.io/name: letro-server
    spec:
      containers:
        - name: server
          image: dev.local/letro-server
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb.default
            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: credentials
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongodb_password
            - name: MONGODB_DB
              value: letro
            - name: VAUTH_API_URL
              value: http://veraid-authority.example
            - name: VAUTH_API_AUDIENCE
              value: http://veraid-authority-audience.example

          envFrom:
            - configMapRef:
                name: letro-server

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: letro-server-sink-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: letro-server
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
