title: "Letro’s VeraId server"

markdown: kramdown

baseurl: /letro-server
destination: ../build/docs
remote_theme: pmarsceill/just-the-docs@v0.7.0

aux_links:
  "GitHub project":
    - "//github.com/relaycorp/letro-server"

footer_content: "Copyright &copy; 2023 by Relaycorp, Inc."

color_scheme: dark

search_enabled: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
